In [4]:
import numpy as np
import torch
from torchmetrics import ConfusionMatrix

In [21]:
target = torch.tensor([], dtype=torch.int32)
preds = torch.tensor([])

target = torch.cat((target, torch.tensor([1, 1, 0, 0])), -1)
preds = torch.tensor([0, 1, 0, 0])
print(target)
print(preds)


tensor([1, 1, 0, 0])
tensor([0, 1, 0, 0])


In [22]:
confmat = ConfusionMatrix(num_classes=2)
abc = confmat(preds, target)
print(abc)

tensor([[2, 0],
        [1, 1]])


In [29]:
x = torch.rand(36, 36)
print(x) # prints the truncated tensor
torch.set_printoptions(threshold=100_100)
print(x) # prints the whole tensor

tensor([[5.8221e-01, 5.3295e-01, 3.8036e-01, 2.8993e-01, 7.3569e-01, 1.1596e-01,
         3.8145e-02, 7.4405e-01, 6.6219e-01, 3.0276e-01, 2.8080e-01, 6.4287e-01,
         6.1463e-01, 4.0780e-01, 5.7602e-01, 9.3669e-01, 2.7441e-01, 6.5958e-01,
         1.6348e-02, 8.0540e-01, 2.6940e-01, 1.6545e-01, 9.5563e-01, 5.5468e-01,
         9.3890e-01, 7.8569e-01, 5.5390e-01, 5.0616e-01, 5.0767e-01, 8.0190e-01,
         5.3541e-01, 5.6955e-02, 2.8748e-03, 3.7047e-01, 9.5957e-01, 5.1651e-01],
        [5.7458e-01, 1.7751e-01, 4.2872e-01, 9.1805e-01, 7.1053e-01, 9.4571e-01,
         3.6458e-01, 4.5879e-01, 3.6147e-01, 6.2514e-01, 4.8392e-02, 2.3564e-01,
         4.0850e-01, 2.4200e-01, 9.3033e-01, 7.3857e-01, 7.3481e-01, 3.6046e-01,
         1.9026e-01, 6.1171e-01, 2.4524e-01, 8.6800e-01, 4.2058e-02, 4.4789e-01,
         8.5979e-01, 2.4820e-01, 1.7542e-01, 1.6758e-01, 2.0572e-01, 9.3208e-01,
         7.2825e-01, 5.1111e-01, 4.7487e-01, 3.6608e-01, 9.6342e-01, 8.2067e-01],
        [4.8058e-01, 7.932