In [27]:
import numpy as np
import torch

In [28]:
data = [[1, 2], [3, 4], [5, 6]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [22]:
p_data = x_data.permute(1, 0)
print(p_data)

tensor([[1, 3, 5],
        [2, 4, 6]])


In [23]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [29]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3221, 0.2778],
        [0.6160, 0.0547],
        [0.7382, 0.6900]]) 



In [31]:
shape = (
    2,
    3,
)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3172, 0.9880, 0.9010],
        [0.5939, 0.4806, 0.6765]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
