In [1]:
import numpy as np
import torch
from torchmetrics import ConfusionMatrix

In [2]:
target = torch.tensor([], dtype=torch.int32)
preds = torch.tensor([])

target = torch.cat((target, torch.tensor([1, 1, 0, 0])), -1)
preds = torch.tensor([0, 1, 0, 0])
print(target)
print(preds)


tensor([1, 1, 0, 0])
tensor([0, 1, 0, 0])


In [3]:
confmat = ConfusionMatrix(num_classes=2)
abc = confmat(preds, target)
print(abc)

tensor([[2, 0],
        [1, 1]])


In [5]:
x = torch.rand(36, 36)
print(x) # prints the truncated tensor
torch.set_printoptions(threshold=10000_10000)
print(x) # prints the whole tensor

tensor([[6.6283e-01, 2.2389e-01, 6.4043e-01, 5.6135e-01, 9.0201e-01, 5.8747e-01,
         9.6989e-01, 4.3415e-01, 5.3649e-01, 6.8650e-01, 8.5734e-01, 7.3368e-01,
         9.4989e-01, 6.3211e-01, 8.8606e-01, 8.6089e-01, 3.5946e-01, 5.2739e-02,
         3.4550e-02, 1.1639e-01, 5.1318e-01, 6.3801e-01, 4.0236e-01, 2.3534e-01,
         2.3880e-01, 5.1162e-01, 6.8765e-01, 2.2509e-01, 5.7500e-01, 9.6288e-01,
         1.3575e-01, 2.0623e-05, 5.5084e-01, 3.1621e-01, 4.4643e-01, 9.7701e-01],
        [8.5220e-01, 5.9981e-01, 3.1454e-01, 5.9113e-01, 6.3672e-01, 1.2297e-01,
         4.6081e-01, 7.8526e-01, 3.1963e-01, 7.0478e-01, 4.6713e-01, 8.5849e-01,
         9.5885e-01, 1.2350e-01, 9.9459e-01, 3.4978e-01, 5.2640e-01, 3.2014e-01,
         8.9265e-01, 3.1437e-01, 1.8036e-01, 8.5304e-01, 1.1757e-01, 5.4755e-01,
         6.4074e-01, 7.8508e-01, 1.6994e-01, 7.6530e-01, 7.4175e-01, 9.2325e-01,
         3.9140e-01, 2.2298e-02, 9.1547e-01, 2.0481e-01, 8.3665e-01, 5.9516e-01],
        [1.8123e-03, 6.868